version: '3.3'

services:
  nodejs:
    build:
      context: ./portail-client-api
      dockerfile: Dockerfile
    image: portal-client-api
    container_name: portail-client-api
    restart: unless-stopped
    env_file: .env
    # environment:
    #   - MONGO_USERNAME=$MONGO_USERNAME
    #   - MONGO_PASSWORD=$MONGO_PASSWORD
    #   - MONGO_HOSTNAME=db
    #   - MONGO_PORT=$MONGO_PORT
    #   - MONGO_DB=$MONGO_DB
    ports:
      # - ${APIPORT}:${APIPORT}
      - 3001:3001
    volumes:
      - ./portail-client-api:/usr/src/portail-client-api
      - ./portail-client-api/node_modules:/usr/src/portail-client-api/node_modules
    networks:
      - portal-client-network
    command: npm start

# ./wait-for.sh db:27017 --

  react-app:
    build:
      context: ./client-portail-web-app
      dockerfile: Dockerfile
    image: client-portail-web-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./client-portail-web-app:/usr/src/client-portail-web-app
      - ./client-portail-web-app/node_modules:/usr/src/client-portail-web-app/node_modules

networks:
  portal-client-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: